CREATE OR REPLACE PROCEDURE total_emp_by_dept_id (
  p_id IN EMPLOYEES.DEPARTMENT_ID%TYPE,
  p_count OUT NUMBER
) IS
BEGIN
SELECT COUNT(*) INTO p_COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID = p_id;
END total_emp_by_dept_id;